version: '3.7'
volumes:
  app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    network_mode: host
    restart: always
    volumes:
      - app:/app/
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    build: ./.docker/php-fpm/
    container_name: php-fpm
    network_mode: host
    restart: always
    volumes:
      - app:/app/

  mysql:
    image: mysql:latest
    container_name: mysql
    network_mode: host
    restart: always
    volumes:
      - ./migrations.sql:/docker-entrypoint-initdb.d/dump.sql
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
